module.exports.authController = require('./auth.controller')
module.exports.userController = require("./user.controller")
module.exports.subjectController = require("./subject.controller")
module.exports.topicController = require("./topic.controller")
module.exports.streamController = require("./stream.controller")
module.exports.teacherController = require("./teacher.controller")
module.exports.questionController = require("./question.controller")
module.exports.testController = require("./test.controller")